name: RecReports
main: me.petersoj.RecReportsPlugin
author: Petersoj
version: 1.0
description: A player reporting and recording plugin to prevent all types of hacking and behavior.
commands:
  report:
    description: Report a player who might be hacking.
    aliases: [recreport, recreports, reports]
    permission: recreports.report
  viewreports:
    description: Open the report selection view.
    aliases: [viewreport, vr]
    permission: recreports.viewreports
permissions:
  recreports.report:
    default: true
  recreports.viewreports:
    default: op